# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2a5a4d444cb51e26e0025f9fa791a31bf5bacbfb81ab6a25ab1b8fb964fa07380892b40e8b9afabac75560fa4c11212ac0f0a9c1c4db0304e8b627d35ac768a

test:
  secret_key_base: 7ab9864650b5cdc9060660e9878bedf48fd86ae8ab08f6591c35f5eebb6beaef986126a0a7620426cd04ecf3544aa75c2f1f82eea39b5752a3ee8e9e18654cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
